# Generated by Django 5.2.10 on 2026-01-21 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(help_text='пить воду/бегать', max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('title', 'place', 'action', 'user')},
        ),
    ]
